spring.application.name=spring-batch-study

# MariaDB
spring.datasource.url=jdbc:mariadb://192.168.0.29:3306/study
spring.datasource.username=study
spring.datasource.password=study1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Batch 메타 테이블 자동 생성
spring.batch.jdbc.initialize-schema=always

# DataSource / JDBC
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.boot.jdbc=DEBUG

# HikariCP
logging.level.com.zaxxer.hikari=DEBUG

# Hibernate DB 연결
logging.level.org.hibernate.engine.jdbc=DEBUG

# Spring Batch
logging.level.org.springframework.batch=DEBUG